---
title: "ESS580 Homework 1: Discharge Data"
author: "Amanda Hastings"
date: "`r Sys.Date()`"
output: 
  
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dataRetrieval)
library(dygraphs)
library(xts)
library(revealjs)
```

# Methods 

## Site Description

# ![]

## Data Acquistion and Plotting Tests

## Data Download 

```{r downloader}
DischargeData <- readNWISdv(
  siteNumbers = '06752260',
  parameterCd = '00060',
  startDate = '2017-01-01',
  endDate = '2022-01-01') %>%
  rename(discharge = 'X_00060_00003')
```

## Static Data Plotter 

```{r, warning = FALSE, fig.width = 8, fig.height = 5}
ggplot(DischargeData, aes(x = Date, y = discharge)) + 
  geom_line() + 
  ylab('Q (cfs)') + 
  ggtitle('Discharge in the Poudre River, Fort Collins, CO')
```


## Interactive Data Plotter 

```{r interactive data plotter}
discharge_xts <- xts(DischargeData$discharge, order.by = DischargeData$Date)

dygraph(discharge_xts) %>%
  dyAxis("y", label = "Discharge (cfs)")
```

# Assignment Items 

## Dygraphs example(s)
```{r interactive data plotter(points)}
dygraph(discharge_xts) %>%
  dyOptions(drawPoints = TRUE, pointSize = 2) %>%
  dyAxis("y",label = "Discharge (cfs)")
```



## Cache la Poudre River 



